// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwDc2QLYo0MbKeV6bvhFNlSILFoLvafc4',
    appId: '1:868942221279:web:72f4af91dc7f3aa26d7e6a',
    messagingSenderId: '868942221279',
    projectId: 'heart-note-555f3',
    authDomain: 'heart-note-555f3.firebaseapp.com',
    storageBucket: 'heart-note-555f3.firebasestorage.app',
    measurementId: 'G-5ZTLVWBHSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAScefOPyt8YVykU6T8KXMUi5oLTrwRSDM',
    appId: '1:868942221279:android:7b8162a9e9a780fd6d7e6a',
    messagingSenderId: '868942221279',
    projectId: 'heart-note-555f3',
    storageBucket: 'heart-note-555f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS6yj-EgcE-IKl5tqZCfVg9q9cCz5-cMY',
    appId: '1:868942221279:ios:78a65e88affa55a06d7e6a',
    messagingSenderId: '868942221279',
    projectId: 'heart-note-555f3',
    storageBucket: 'heart-note-555f3.firebasestorage.app',
    iosBundleId: 'com.lime.heartnote',
  );
}
